---
title: "About me"
output: 
  html_document:
    toc: true
    toc_float: true
---



I was a new manager five months before the pandemic and drove our group's migration to Microsoft Teams a few months before the pandemic. Since then, finding ways to drive win-win solutions for employer _and_ employees has been essential. Since 2021, I have more than doubled direct-report staff and retained them. As a project manager, I have worked with a diverse group to track and execute all project deliverables. 

# Integrating Processes 

My motto can be boiled down to Integration, Implementation, and Innovation. And the fourth _I_ is Intersection, but that's not as catchy. At the crux of Public Health is bringing multiple stakeholders to the table to answer questions and I have several years experience bringing multiple specialists to address process gaps and innovate new workflows. 


# Education & Public Health

I have been in the research world focusing on mental and behavioral health since 2017. I am currently a 2nd - year Masters Student in Mailman where I focus on Health Policy and Management and Applied Biostatistics and Public Health Data Science at the Columbia Mailman School of Publich Health.


# Technology

I have worked in the digital mental health space working with an interdisciplinary group to launch two web applications.This process led me from beta - testing UI/UX for accessibility in Spanish and English to designing tests to assess the robustness of how the mapped algorithms functioned.


# Finance

My comfort using advanced formulas and creating dashboards in Excel have allowed me to track activity fees, recruitment targets, and project spending. Through my coursework I have augmented my ability in Accounting and Budgeting, as well as the benefits of using Tableau, SAS, and R to answer data analytic questions.

# Mentorship 

I am a proud member of a DEI group that is focused on equitable access to mentorship opportunities for non-faculty staff. My work has inspired me to lead multiple mini-1-on-1s and applied workshops with interested staff to cover best practices, Excel formulas and dashboards. My education has refined this drive and increased my capacity to widen my offerings.