---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```


```{r data, include = FALSE}
data("rest_inspec")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: How do Health Inspection Grades vary by borough?

```{r}
rest_inspec %>% 
  slice_sample(n = 1000) %>%
  drop_na(grade) %>% 
  mutate(
      grade = factor(grade, levels = c("A", "B", "C", "Z", "Not Yet Graded"))) %>% 
  filter(
    critical_flag != "Not Applicable", 
    grade != "Not Yet Graded", 
    grade != "P",
    grade != "Z"
  ) %>% 
  separate(grade_date, into = c("year", "month", "day"), sep = "-") %>% 
  group_by(grade, boro, year) %>%
  summarize(
    n_obs = n()) %>% 
  plot_ly(
    x = ~n_obs, y = ~grade, color = ~boro, 
    type = "bar", mode = "markers",
    alpha = .5
  ) %>% 
  layout(xaxis = list(title = '# of Graded Events'), 
    yaxis = list(title = 'Grade'), legend = list(title = list(text = '<b>Boro')))
                                                            
 
```

### Chart B: What is the distribution of "critical" violations per grade?

```{r}
  rest_inspec %>% 
  slice_sample(n = 1000) %>% 
  drop_na(grade) %>% 
  mutate(
      grade = factor(grade, levels = c("A", "B", "C", "Z", "Not Yet Graded"))
  ) %>% 
  group_by(grade, critical_flag) %>%
  filter(
    critical_flag == "Critical"
  ) %>%
  summarize(
    n_obs = n()
  ) %>%
  plot_ly(
    x = ~grade, y = ~n_obs, 
    type = "bar"
  ) %>% 
  layout(xaxis = list(title = 'Grade'), 
    yaxis = list(title = '# of Critical Violations'), legend = list(title = list(text = '<b>Boro')))
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart C: Where can I get the "safest" Grade A pizza?

```{r}
rest_inspec %>% 
  slice_sample(n = 1000) %>%
  drop_na(grade) %>% 
  mutate(
    zipcode = as.character(zipcode)
  ) %>% 
  filter(
    grade == "A",
    cuisine_description == "Pizza") %>% 
  mutate(
    dba = as.factor(dba),
    dba = fct_reorder(dba, score)
  ) %>% 
  mutate(
    address = str_c(dba,"\n", street,",", zipcode)) %>% 
  plot_ly(
  x = ~score, y = ~dba, color = ~boro,
type = "bar", mode = "markers",
alpha = .5, text = ~address
  ) %>% 
  layout(xaxis = list(title = 'Score'), 
    yaxis = list(title = 'Place'), legend = list(title = list(text = '<b>Boro')))
  
```

